---
- name: Download sources
  get_url:
    url: '{{ sql_url }}'
    dest: /opt/mysql

- name: Install package
  yum:
    name: '{{ sql_url }}'
    state: present

- name: Install MySQL
  yum: 
    name: mysql-server 
    state: present


    
